version: '3'
services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    links:
      - db
  db:
    build: ./mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
        - mongo-data:/data
volumes:
  mongo-data:
    driver: local
